#!/bin/sh

CONFIG=$(dirname "$0")
DIR=$(pwd)
if [ "Windows_NT" = "$OS" ]; then
  CONFIG=$(cygpath -m "$CONFIG")
  DIR=$(cygpath -m "$DIR")
fi

cd "$(dirname "$(realpath "$0")")"
xp xp.glue.Glue -c "$CONFIG/glue.ini" -d "$DIR" "$@"
